name: Publish Docs

env:
    Version: 0.0.1
    NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.100

            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'


            - name: Publish Docs to github pages
              env:
                  GH_PUSH_TOKEN: ${{secrets.GH_PUSH_TOKEN}}
              run: |
                  npm install
                  git config --global user.name 'ElderJames'
                  git config --global user.email 'shunjiey@hotmail.com'
                  dotnet build
                  dotnet publish -c Release -o tmp
                  cd tmp/AntBlazor.Docs.ClientApp/dist
                  rm index.html
                  cp -r gh-pages/* gh-pages/.nojekyll ./
                  rm -r gh-pages
                  git init
                  git checkout -b gh-pages
                  git add -A
                  git commit -m "docs: Create build $GITHUB_RUN_ID"
                  git push -f https://ElderJames:$GH_PUSH_TOKEN@github.com/ElderJames/ant-design-blazor.git gh-pages

            - name: Package Nightly Nuget
              run: |
                  dotnet pack components/AntBlazor.csproj /p:PackageVersion=$Version-nightly-${GITHUB_RUN_ID} -c Release -o pack-${GITHUB_RUN_ID} --no-build --no-restore

            - name: Publish to Nuget
              run: |
                  dotnet nuget push pack-${GITHUB_RUN_ID}/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
