# Each PR will build preview site that help to check code is work as expect.

name: Preview Build

on: pull_request

jobs:

  build-site:
    name: build preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.100

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.101

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100
      
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Prepare AOT workload
        run: |
          dotnet workload install wasm-tools

      - name: build site
        id: site
        run: |
          dotnet --list-sdks
          npm install
          dotnet build
          sed -i s/{version}/$PACKAGE_VERSION/g ./site/AntDesign.Docs/Shared/HeaderMenu.razor
          dotnet publish ./site/AntDesign.Docs.Wasm -c Release -f net8 -o _site
        env:
          PACKAGE_VERSION: ${{ github.event.number }}

      - name: upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site/wwwroot/
          retention-days: 5

      # Upload PR id for next workflow use
      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt
