name: Publish Docs with AOT

on:
  push:
    tags:
      - "*"

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Prepare AOT workload
        run: |
          dotnet workload install wasm-tools

      - name: Publish Docs 🎉
        id: publish
        run: |
          VERSION=`git describe --tags`
          echo "::set-output name=package_version::${VERSION}"
          npm install
          echo "/* updated `date "+%Y-%m-%d %H:%M:%S"` */" >> ./site/AntDesign.Docs.Wasm/wwwroot/service-worker.published.js
          sed -i s/{version}/$VERSION/g ./site/AntDesign.Docs/Shared/HeaderMenu.razor
          sed -i s/{version}/$VERSION/g ./site/AntDesign.Docs.Wasm/wwwroot/version.json
          dotnet build
          dotnet publish ./site/AntDesign.Docs.Wasm -c Release -f net6 -o cargo -p:EnableAOT=true
          
      - name: Prepare for devops gitee pages
        id: publish
        run: |
          VERSION=`git describe --tags`
          cp -rf scripts/gitee-pages/* scripts/gitee-pages/.spa ./cargo/wwwroot
          sed -i s/{version}/$VERSION/g ./cargo/wwwroot/index.html

      - name: Deploy to Gitee 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PUSH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./cargo/wwwroot
          force_orphan: true

      - name: Prepare for devops github pages
        id: publish
        run: |
          VERSION=`git describe --tags`
          cp -rf scripts/gh-pages/* scripts/gh-pages/.nojekyll ./cargo/wwwroot
          sed -i s/{version}/$VERSION/g ./cargo/wwwroot/index.html

      - name: Deploy to Github.io 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PUSH_TOKEN }}
          external_repository: ant-design-blazor/ant-design-blazor.github.io
          publish_branch: master
          publish_dir: ./cargo/wwwroot
          cname: antblazor.com
          force_orphan: true
          tag_name: ${{ steps.publish.outputs.package_version }}

      - name: Sync to Gitee 💕
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:ant-design-blazor/ant-design-blazor.git"
          destination-repo: "git@gitee.com:ant-design-blazor/ant-design-blazor.git"
